### ISSUE TITLE
feature request - allow upload_sample() to upload files which are already opened 

### ISSUE THREAD

**Issue by lazydaemon** [CIRCL/PyMISP#101]
Right now, the upload_sample() function will always try to open an existing file from somewhere on the filesystem. In my case, the file comes from an api which means it's already represented as bytes. Of course, I could temporarily save the file and use the upload_sample() function with the temporary filepath but I think it would be nicer if the upload_sample() would provide that function. Maybe, letting the user open and encode the file by himself  is a better option here.

**Comment by Rafiot** [comment]
Done :)
