### ISSUE TITLE
new_event function not taking Org_id and Orgc_id

### ISSUE THREAD

**Issue by Doog87** [CIRCL/PyMISP#103]
I created a simple script to add an event to my MISP instance.

My MISP instance has two Organisations (1. Patricks Org (id=1) 2. Another Org(id=10))

Example script is below. I can successfully add an event, but it always is sets it to Patricks Org (id=1). Even when I tell it that org_id and orgc_id are equal to 10(Another Org). 

Is this intended behavior? It seems directly tied to the user's api key and what organisation they are a part of in MISP. Basically it seems to ignore that I am defining the organisation that I want the event to be associated to.

Thank you!

**Side note: I notice when i import an event in JSON to MISP it does head the org_id and orgc_id being set.

```
from pymisp import PyMISP

misp_url = 'https://xxxx.misp.com'
misp_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
misp_verifycert = True

def init(url, key):
    return PyMISP(url, key, misp_verifycert, 'json')

misp = init(misp_url, misp_key)

def create_dummy_event(misp):
    event = misp.new_event(0, 4, 0, 'dummy event', '', 'False', 10, 10)

create_dummy_event(misp)      



```

**Comment by Rafiot** [comment]
The orgid you pass in the JSON file is ignored by the server. If you want to create events for different organisations, you need to use the API key of those different organisations.
