### ISSUE TITLE
Documentation lists non-existant API's for version on Documentation.

### ISSUE THREAD

**Issue by SparkyNZL** [CIRCL/PyMISP#108]
Hi,

Ive been trying to get my python script to add a tag to an event but its not working, turns out that the documentation for 2.4.50 https://media.readthedocs.org/pdf/pymisp/master/pymisp.pdf lists a number of API;s which are missing

misp.tag
misp.untag

Ive had a look at api.py for version 2.4.50 , 56 and these calls do not exist. :(

Perhaps an edit of the documentation ? or change the version number on the doco ?

Anyhow since Im using 2.4.56 what command do i use to add a custom tag to an event ?

currently im using using

misp.add_tag(event, 130) which is fine, but i would like to specify an actual name not a number, is this possible ?

eg
misp.add_tag(event, 'MyTag')

Cheers

**Comment by Rafiot** [comment]
read the doc build is now fixed.
