### ISSUE TITLE
Inaccurate error message when API key is wrong

### ISSUE THREAD

**Issue by edhoedt** [CIRCL/PyMISP#113]
Using `PyMISP(url,key,True,'json')` returns an incorrect warning if the key is wrong.

> Unable to check the recommended PyMISP version (MISP <2.4.60), please upgrade.

**Comment by Rafiot** [comment]
Fixed by https://github.com/CIRCL/PyMISP/commit/5f94ad31047f87716a17012812e9a7ec09bf4a20
