### ISSUE TITLE
Published flag on search method does not work when the value is set to 0

### ISSUE THREAD

**Issue by grails-coder** [CIRCL/PyMISP#114]
Whenever I issue a search query with parameter _published_ set to _0_ and the event is already marked as published, the query still returns the event that is in published state.

Code snippet:
`
search_params = {
                        'org': 'MYORG',,
                        'published': 0,
                        'date_from': '2017-07-31',
                        'date_to': '2017-07-31'
        }`
`self.handler = PyMISP(url='url',
	key='key',
	ssl=(ssl_enabled == "True"),
	cert=('cert_path', 'cert_key')
)`
`
search_result = self.handler.search(**search_params)
print(search_result)
`
I'd expect following response to be returned:
`{'name': 'No matches.', 'message': 'No matches.', 'url': '/events/restSearch/download', 'errors': ['No matches.']}`
However I always get the event (published) back even though I'm looking for the non-published ones.

I also tested the case whenever the Event is _not published_ and I send the search query with _published_ flag set to _1_ in which case the filter is correctly applied.

Two different versions of PyMisp have been tested: 2.4.68, and 2.4.77(latest at the time of writing), both present the same issue.

**Comment by Rafiot** [comment]
I did some changes in the search method (https://github.com/CIRCL/PyMISP/commit/fe829b8f4d5f62eb2e0aa702ec8b5967875ae0c5) but is shouldn't fix it (also, I don't understand why it doesn't work properly, as the parameter should be passed properly.

Just in case, can you give a try with trunk (`pip install git+https://github.com/CIRCL/PyMISP.git`) and let me know if it works better. If not, I'll figure it out with @iglocska

**Comment by grails-coder** [comment]
Thanks for the quick response @Rafiot, I already tried the trunk you provided, results are the same as before, _published_ filter is not filtering events, thus returned information remains wrong. 
I also tried the same query via curl, just to make sure it was (or not) a problem on PyMISP, I've noticed the response from MISP API is also incorrect, so I'd conclude the error is not because of PyMISP but because a bug on MISP API itself.
Here the curl query I issued, I believe it's the equivalent to the PyMISP search call:
`curl --insecure --key mycert.key.pem --cacert mycert.ca.pem --cert mycert.pem:cer_password_goes_here -i -H "Accept: application/json" -H "Authorization: MISP_KEYAPI" -H "content-type: application/json" -d '{"org": "MYORG", "from": "2017-07-31", "to": "2017-07-31", "published": "0"}' -X POST https://<misp_url>/events/restSearch/download`

**Comment by Rafiot** [comment]
@iglocska wink wink, for after the objects :)

**Comment by iglocska** [comment]
It kind of works, but it's not great. "published":1 will return all published events only, "published":0 will ignore the filter. Will change it.

**Comment by iglocska** [comment]
Should be fixed now, just git pull please.

**Comment by Rafiot** [comment]
Thanks!

**Comment by grails-coder** [comment]
Thanks as well
