### ISSUE TITLE
Mass IP lookup

### ISSUE THREAD

**Issue by zoni171** [CIRCL/PyMISP#119]
Is there a way (fast) to mass query lets say 4k IPs or domains?
What is the easiest way? PyMISP? Can I them export the results with details about the even and w/e comments on the enries itselves?
What would be the command(s)?

**Comment by Rafiot** [comment]
There are many options, it totally depends on how you want to do it.
1. https://<URLs>/attributes/search is one, it will give you a full list of all the events related to what you're searching. You just need to filter out the data you don't want afterwards.
2. PyMISP: `search`, it should be done relatively fast and you will get full events in json and need to filter out
3. If you want to repeat it very often, you can use hashstore: https://github.com/MISP/misp-workbench/tree/master/hashstore and possibly tweak it so the database contains exactly what you want.
