### ISSUE TITLE
What it the correct license?

### ISSUE THREAD

**Issue by joachimmetz** [CIRCL/PyMISP#16]
setup.py says: GNU General Public License v3 (GPLv3)

LICENSE: is (from a first glance) BSD 2 clause

pymisp/api.py does not contain the necessary GPL headers

What it the correct license?

**Comment by Rafiot** [comment]
Woops, thanks for the report, fixed now (BSD 2 clause)

**Comment by joachimmetz** [comment]
Thanks for correcting this.
