### ISSUE TITLE
feature request - add/remove tags to events

### ISSUE THREAD

**Issue by elhoim** [CIRCL/PyMISP#17]
Freshly added today in MISP, the possibility to add & remove tags on events in https://github.com/MISP/MISP/commit/01398b3aded744d557f2cf12ccd40098b0b25ffe

**Comment by Rafiot** [comment]
For that, we need to be able to fetch the list of existing tags => https://github.com/CIRCL/PyMISP/issues/6#issuecomment-135422455

**Comment by Rafiot** [comment]
Solved too.
