### ISSUE TITLE
{u'url': u'/events', u'name': u'Invalid event.'}

### ISSUE THREAD

**Issue by seblau** [CIRCL/PyMISP#19]
I am getting the following error with the newest PyMISP: `{u'url': u'/events', u'name': u'Invalid event.'}` after trying to add a new event: `response = misp.new_event(distribution=0, threat_level_id=4, analysis=0, info="Python API Test")`.

The MISP version is 2.2. Maybe the new PyMISP is not compatible with MISP 2.2?

Any suggestions?

**Comment by Rafiot** [comment]
No, the newest PyMISP is only compatible with MISP 2.3, and I highly recommend to always use the latest hotfix.
