### ISSUE TITLE
Get error 404/405 when trying to add/update an event

### ISSUE THREAD

**Issue by didelphodon** [CIRCL/PyMISP#3]
While searching through the API (search-method) works as expected add_event/update_event result in 404/405 errors.

My examplary update scenario: I searched for a specific event => found => retrieved event from the result => changed the "org" value => tried to update (update_event method) the event using modified event object => results in 405

The add_event scenario was analog and resulted in 404.

What went wrong? Any ideas?

**Comment by adulau** [comment]
Not sure if changing the ORG value is really possible. Have you tried with another attributes?

**Comment by didelphodon** [comment]
Not yet, which one should work?

**Comment by adulau** [comment]
Any other attributes should work. ORG is fixed as it should not change (confirmed https://github.com/MISP/MISP/issues/453).

**Comment by didelphodon** [comment]
Tried other attributes but without luck.
I also thought that - as I just copied the event-object beforehand (as mentioned above) - the ID might be the problem and cleared the ID field but without luck, again.
For more information ... a little excerpt of the result-object (Response):
...
text = u'{"name":"Invalid event.","url":"\\/\\/events?%2Fevents="}'
...

**Comment by didelphodon** [comment]
The following changes in the PyMISP API code made the add_event method work as expected ...
Line 48: 'content-type': 'application/' + out})
Line 87: return session.post(self.url, data=json.dumps(event))
Line 97: return session.post(self.rest.format(event_id), data=json.dumps(event))

I have to say that line 97 is just a guess, though - it also didn't use the string representation of the JSON object just like in line 87 so I thought it was/is wrong, too.

However, I'm still having issues with update_event as it returns me 200 but "message":"Error" as a content.

**Comment by didelphodon** [comment]
What about adding those modifications (lines 48, 87, 97) I mentioned?

**Comment by Rafiot** [comment]
Sorry for the very late answer, the code of the API had been massively reworked and everything should work properly now.
