### ISSUE TITLE
error in upload_attachment

### ISSUE THREAD

**Issue by truckydev** [CIRCL/PyMISP#33]
Hi team,

There is an error in line 632 and 634 : 

the line 
`return self._upload_sample(to_post)` 
should be 
`return self._upload_attachment(to_post)`

no ?

**Comment by Rafiot** [comment]
That's true, I'm fixing it right now...

**Comment by Rafiot** [comment]
Nervermind, this function doesn't make any sense and should not have been implemented: uploading an attachment can already be done by uploading an external analysis.

Removing it.

**Comment by Rafiot** [comment]
If you want to upload an attachment without the to_ids flag, you can do it with the upload sample function.

**Comment by truckydev** [comment]
when I try to upload an attachment (not a sample) like this : 

```
print misp.upload_attachment(
				"sample.pdf", # or sample.ioc
				sampleFile,
				1,# event id
				0, # distribution
				False, # to ids
				"External Analysis", # category
				"test", # comment
				2, #analysis
				1)# threat
```
The return is : 
`{u'url': u'/events/view/14', u'message': u'Success, saved all attributes.', u'name': u'Success', u'id': 1}
`
But file is uploaded as sample and not like attachement.

The function was created to simplify the type of upload.
Or maybe a better way ?

**Comment by Rafiot** [comment]
You're right, the API on the server ignores those parameters. This is a issue we should fix.

@iglocska can you have a look at it, please?

**Comment by Rafiot** [comment]
You're right, the API on the server ignores those parameters. This is a issue we should fix.

@iglocska can you have a look at it, please?

**Comment by iglocska** [comment]
On it!

**Comment by truckydev** [comment]
Thx :)

**Comment by truckydev** [comment]
Some news ?

**Comment by iglocska** [comment]
Oh sorry. Pushed this yesterday: 
https://github.com/MISP/MISP/commit/1f7bb46c1df0c075aef87f8d458bd2106d2995d8

It should now detect whether the IDS flag is set, if yes, it will create an attachment instead of a sample. Just git pull to get it.

**Comment by Rafiot** [comment]
Thanks!

**Comment by truckydev** [comment]
Good news thx
