### ISSUE TITLE
add_tag and new tag run away from new version

### ISSUE THREAD

**Issue by truckydev** [CIRCL/PyMISP#35]
Hi there,

my script no longer works because `new_tag` and `add_tag` ​​functions are in the PyMISP but I have en error 500.

if is not an error : 
what is the new way to create and add a tagg to an event by the API?
this feature was very useful

I have an Apache error on ligne 2618 in MISP/app/Controller/EventsController.php with $RearrangeTool = new RequestRearrangeTool(); not found.

thanks again

**Comment by tomking2** [comment]
I've just tested with an updated MISP (2.4.34), and no issues exist in my instance. Probably nothing to do with PyMISP, looks like a missing function in the PHP script and your MISP instance.

**Comment by tomking2** [comment]
Do you have a php located in app/Lib/Tools/RequestRearrangeTool.php ?

**Comment by truckydev** [comment]
Yes I have :(

**Comment by truckydev** [comment]
I see there are this function in pymisp.

maybe a probleme whith my instance of misp.

**Comment by tomking2** [comment]
Hmm, this is strange. Looks like you will get better guidance on the other post.

If you run this command on your root MISP directory (likely /var/www/MISP), what files come back?
```grep -rl "RequestRearrangeTool" ./```

I've got three references (ignoring .git/index):
- EventsController.php (you'll have this as it's producing the error)
- AppController.php (this should have a line which references the tool, if not, you're missing something in this file)
- myapp_cake_core_file_map (Not entirely sure, but I think this is a automatically generated file. But it points to the file and makes a map, probably is needed to work also)

**Comment by truckydev** [comment]
My file AppController was the bad version. Problème solve

thx :)

**Comment by Rafiot** [comment]
Thx!
