### ISSUE TITLE
Error with Some function in  PyMISP

### ISSUE THREAD

**Issue by truckydev** [CIRCL/PyMISP#36]
Hello team,

the "info" field of the upload_sample and upload_samplelist function with PyMISP does not work.
The value displayed in the " Comment " (web interface) is always empty.
I try to upload file as attachment not sample.

Here an exemple:
``` python
misp.upload_sample(
    "my_sample_filename", # filename
    "sample.pdf", # file
    "1", € event_id
    "0", # disctribution
    "False" # to ids = as attachment
    "External analysis",
    "my comment for the pdf", # < = don't  work
    )
```

I have an error whith misp.add_hashes too:
upload a filename alone don't work but with a MD5 it's ok.
a MD5 alone work too
and just a filename work by the web interface.

For just a filename I don't think "add_pattern" is the right solution. add_hashes look good because wee can find the right description "filename" in the web interface"

Can you take a look ?
thx

**Comment by adulau** [comment]
We updated MISP API to be able to include comment in upload sample. https://github.com/MISP/PyMISP/pull/14/files#diff-0 and PyMISP has been updated to include add filename function https://github.com/MISP/PyMISP/pull/14/files#diff-0. 

Could you check if everything is fine for you? Thank you.

**Comment by truckydev** [comment]
Hi

Thx ^^
add_filename work great :)

for upload_sample : add comment don't work :(
when I do : 
```python
print upload_sample( .........)
```
message is `Success, ...` but no comments visible to the web interface.

**Comment by adulau** [comment]
Sorry, it's also fixed now https://github.com/CIRCL/PyMISP/commit/089b0a72b02887611b07a330d3751ecb2c563f3e. Thank you.

**Comment by truckydev** [comment]
All right now :)

Thanks :+1:

**Comment by adulau** [comment]
You're welcome. Glad it works for you. Anyway thank you for the feedback.
