### ISSUE TITLE
Missing tags and categories for MISP attributes

### ISSUE THREAD

**Issue by certau-davidg** [CIRCL/PyMISP#37]
A number of MISP v2.4.33 categories and types are missing within the "api.py" lists:
  self.categories = []
  self.types = []

Within our own scripts we have implemented a patch to extend these lists at execution until the issue is able to be fixed:
objPyMISP.categories.append('Financial fraud')
objPyMISP.types.extend(['domain|ip','pdb','btc','iban','bic','bank-account-nr','aba-rtn','bin','cc-number','prtn','campaign-name','campaign-id','malware-type','uri','authentihash','ssdeep','imphash','pehash','sha224','sha384','sha512','sha512/224','sha512/256','tlsh','filename|authentihash','filename|ssdeep','filename|imphash','filename|pehash','filename|sha224','filename|sha384','filename|sha512','filename|sha512/224','filename|sha512/256','filename|tlsh','windows-scheduled-task','windows-service-name','windows-service-displayname','whois-registrant-email','whois-registrant-phone','whois-registrant-name','whois-registrar','whois-creation-date','targeted-threat-index','mailslot','pipe','ssl-cert-attributes','x509-fingerprint-sha1'])

This bug prevents some valid input to _prepare_full_attribute() from executing successfully.

**Comment by Rafiot** [comment]
Fixed by: https://github.com/CIRCL/PyMISP/commit/c269913ad3ba2b03c898ff92b17ff3a6301a5f81
