### ISSUE TITLE
How to remove an attribute?

### ISSUE THREAD

**Issue by didelphodon** [CIRCL/PyMISP#4]
How can one remove an attribute via the update_event method?

**Comment by didelphodon** [comment]
If that's not possible then I'd like to add this as a feature request.

**Comment by Rafiot** [comment]
I don't think it is possible to do that for now, but we will investigate how hard it is to implement.

**Comment by Rafiot** [comment]
It is possible, but not implemented in the API: https://github.com/MISP/MISP/issues/621#issuecomment-135431722 

Working on it.
