### ISSUE TITLE
iocs multiupload

### ISSUE THREAD

**Issue by doomedraven** [CIRCL/PyMISP#42]
after see examples/documentation/api code I don't see the possibility to upload bulk iocs by type or any bulk upload, update events per ioc is pretty slow, did you thought about implement bulk upload?

or if i missed that, point me where/how i can do that

**Comment by adulau** [comment]
FYI, It's now possible via the MISP API to add multiple attributes in one go. https://github.com/MISP/MISP/commit/7ef3f4615ca2523567fff96570f92616a355c8e0 The PyMISP functions should work for simple attributes but might not work for the composite objects.

**Comment by doomedraven** [comment]
thanks for great work, i got notification in twitter,i will check it :)

**Comment by doomedraven** [comment]
hello both, i looked how to make multi iocs upload easy to final user with pymisp, what do you think if we add loop check for iocs in this way?

```
    def add_ipdst(self, event, ipdst, category='Network activity', to_ids=True, comment=None, distribution=None, proposal=False):
        attributes = []
        attributes.append(self._prepare_full_attribute(category, 'ip-dst', ipdst, to_ids, comment, distribution))
        return self._send_attributes(event, attributes, proposal)
```

to

```
    def add_ipdst(self, event, ipdst, category='Network activity', to_ids=True, comment=None, distribution=None, proposal=False):
        attributes = []
        for ip in ipdst.split("\n"):
            attributes.append(self._prepare_full_attribute(category, 'ip-dst', ip, to_ids, comment, distribution))
        return self._send_attributes(event, attributes, proposal)
```
