### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by the4tress** [CIRCL/PyMISP#48]
Is there an easy solution to supporting proxies? I have a situation where I need to use a proxy to communicate with my MISP server.

**Comment by adulau** [comment]
Just wondering, have you tried to set the environment variables (HTTP_PROXY  and HTTPS_PROXY)?

**Comment by Rafiot** [comment]
I didn't try, but all the communication is made via requests, and it seems to support proxies fairly well: http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by the4tress** [comment]
I thought about using the HTTP_PROXY env variable but I need to communicate with some devices without a proxy. I know there is a blacklist variable I can use, but was looking or something more official.

I did write some stuff for requests that I thought would work, but didn't. I'm on the road right now but can share what I worked on when I get back.

**Comment by the4tress** [comment]
So in `__prepare_session` I added session.proxies. This should tell any session.get() methods to use the proxy, correct?

    session = requests.Session()
    session.proxies = {
        'http': 'http://MY_PROXY_SERVER',
        'https': 'https://MY_PROXY_SERVER',
    }
    session.verify = self.ssl

I feel like that is the correct usage, but it isn't hitting my proxy at all.

Any suggestions?

**Comment by the4tress** [comment]
Just a quick ping on this. Does that session proxy look correct above?

Thanks.

**Comment by Rafiot** [comment]
Can you do a tcpdump? That should work.

**Comment by Rafiot** [comment]
I just implemented proxy support to PyMISP directly: just pass the python dict as a parameter to PyMISP and all the queries use the proxies.
