### ISSUE TITLE
PyMISP gives obscure error when API key is invalid

### ISSUE THREAD

**Issue by RichieB2B** [CIRCL/PyMISP#53]
I shouldn't have to use tcpdump to understand what went wrong.
```
$ ./et2misp.py 
Traceback (most recent call last):
  File "./et2misp.py", line 75, in <module>
    init()
  File "./et2misp.py", line 14, in init
    mymisp = PyMISP(url, key)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 118, in __init__
    self.categories = self.describe_types['result']['categories']
KeyError: 'result'
```

**Comment by RichieB2B** [comment]
I think this is because _check_response() doesn't raise an exception for response code 403 (it just sets an error string) while __init__ calls get_version() and expects an exception.

**Comment by Rafiot** [comment]
Thank you for the report, that should be fixed now.
