### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by sebix** [CIRCL/PyMISP#56]
- [x] tests/test.py uses print-statement, breaks on py2 [patch](https://github.com/CIRCL/PyMISP/compare/master...sebix:fix-test.patch) 45379a1158ad922b160914c4446ae92d931c5b3c
- [ ] bogus import [`from keys import url, key`](https://github.com/CIRCL/PyMISP/blob/master/tests/test.py#L5). What should this mean?

**Comment by Rafiot** [comment]
Woops, right, thanks for the patch 

The bogus import imports the URL of the instance and the authkey of the account to use. Same idea as this file: https://github.com/CIRCL/PyMISP/blob/master/examples/keys.py.sample
For obvious reasons, I cannot share a file containing an authkey.

**Comment by sebix** [comment]
So there's no real to do automated tests yet?

A easy way to create them, would we to use [requests-mock](https://pypi.python.org/pypi/requests-mock)

**Comment by Rafiot** [comment]
Hmm, good point I didn't know about requests-mock.
Right now, I test PyMISP in the travis CI of MISP which is clearly suboptimal.

**Comment by sebix** [comment]
> Right now, I test PyMISP in the travis CI of MISP which is clearly suboptimal.

Only for Python2 obviously :)

My usecase: I'd like to execute the tests automatically in the packaging process

**Comment by Rafiot** [comment]
Yeah, seems to be the default on travis :) and I didn't try anywhere else. Can you make a PR with the python3 changes? 

I'll try to write test cases with requests-mock asap.

**Comment by sebix** [comment]
> Yeah, seems to be the default on travis :) and I didn't try anywhere else.

See here for an example: https://github.com/certtools/intelmq/blob/master/.travis.yml#L3

**Comment by Rafiot** [comment]
Mostly there now. More tests are needed, but it is an ongoing project.
