### ISSUE TITLE
PyMISP Broken

### ISSUE THREAD

**Issue by tomking2** [CIRCL/PyMISP#58]
It looks as though the current version of PyMISP is broken, due to the removal of the option of XML/JSON.

For example, on line 129, the prepare session only references "self", and no longer includes the force_out. This is fine, as like the update states, only JSON is being supported moving forward.

However, looking at line 207, it is still passing the force_out variable to this function, which causes python to crash as it is only expecting the one argument (self), but is being passed two.

I'm in the process of updating this, but am awfully busy right now so won't be able to get round to complete it any time soon :(

**Comment by tomking2** [comment]
One more thing - It looks as though during the check_response on a **get(event_id)**, it looks for a status code from the resulting response.

However it seems that MISP is instead responding with the JSON itself, and therefore fails when looking for a response code.

**Comment by Rafiot** [comment]
woops, working on it

**Comment by tomking2** [comment]
Awesome, thanks @Rafiot

**Comment by Rafiot** [comment]
This should be fixed, but I still need the parameter for `__prepare_session` because... reasons. Just hiding it from now on.
