### ISSUE TITLE
Feature request - replace tag

### ISSUE THREAD

**Issue by elhoim** [CIRCL/PyMISP#6]
Create a script using PyMISP to replace tags on a MISP instance and republish the events without email.
The idea is to address the concern highlighted in https://github.com/MISP/MISP/issues/473 with the introduction of hardcoded tags to help with standardisation

**Comment by elhoim** [comment]
https://github.com/MISP/MISP/commit/01398b3aded744d557f2cf12ccd40098b0b25ffe will help with this.

**Comment by Rafiot** [comment]
We need to have a way to get the existing tags from the instance. Linking it to https://github.com/MISP/MISP/issues/473

**Comment by Rafiot** [comment]
You can remove and add tags with PyMISP, closing.
