### ISSUE TITLE
404 on attributes/describeTypes.json

### ISSUE THREAD

**Issue by the4tress** [CIRCL/PyMISP#63]
I'm getting the following error when I try to pull data from MISP:

```
[dev@dev tc_misp]$ python tc_misp.py 
{
    "version": "2.4.21"
}

Status Code: 404

{
    "url": "/attributes/describeTypes", 
    "message": "Not Found", 
    "errors": [
        "Not Found"
    ], 
    "name": "Not Found"
}

Traceback (most recent call last):
  File "tc_misp.py", line 195, in <module>
    main()
  File "tc_misp.py", line 131, in main
    init()
  File "tc_misp.py", line 40, in init
    proxies=proxy)
  File "/home/dev/Projects/ThreatConnect/tc_misp/lib/pymisp/api.py", line 143, in __init__
    self.categories = self.describe_types['result']['categories']
KeyError: 'result'
```

I added this to the line [after the get request](https://github.com/CIRCL/PyMISP/blob/8059ead9cf451f2081f43e88e77938844cde72d5/pymisp/api.py#L132) for `descriptTypes.json` in `api.py`:

        print('Status Code: {}'.format(response.status_code))

Looks like I'm getting a 404 on that file.

Any ideas?

Thanks!

**Comment by adulau** [comment]
Sure. You are running a very old version of MISP. We strongly recommend to upgrade MISP (a git pull would do the job).

**Comment by the4tress** [comment]
Awesome, I'll look into that.

Thanks!
