### ISSUE TITLE
add org during add event creation

### ISSUE THREAD

**Issue by garanews** [CIRCL/PyMISP#69]
a week ago I was modifying the _prepare_full_event and the new_event in api.py in order to accept the org and orgc:

    def _prepare_full_event(self, distribution, threat_level_id, analysis, info, date=None, published=False, org=None, orgc=None):
        to_return = {'Event': {}}
        # Setup details of a new event
        if distribution not in [0, 1, 2, 3]:
            raise NewEventError('{} is invalid, the distribution has to be in 0, 1, 2, 3'.format(distribution))
        if threat_level_id not in [1, 2, 3, 4]:
            raise NewEventError('{} is invalid, the threat_level_id has to be in 1, 2, 3, 4'.format(threat_level_id))
        if analysis not in [0, 1, 2]:
            raise NewEventError('{} is invalid, the analysis has to be in 0, 1, 2'.format(analysis))
        if date is None:
            date = datetime.date.today().isoformat()
        if published not in [True, False]:
            raise NewEventError('{} is invalid, published has to be True or False'.format(published))
        to_return['Event'] = {'distribution': distribution, 'info': info, 'date': date, 'published': published,
                              'threat_level_id': threat_level_id, 'analysis': analysis, 'org': org, 'orgc': orgc}
        return to_return

    def new_event(self, distribution=None, threat_level_id=None, analysis=None, info=None, date=None, published=False, org=None, orgc=None):
        data = self._prepare_full_event(distribution, threat_level_id, analysis, info, date, published, org, orgc)
        response = self.add_event(data, 'json')
        return self._check_response(response)

it was working 

![image](https://cloud.githubusercontent.com/assets/16938405/19927736/4b80b5b8-a0fb-11e6-8340-f6483e271518.png)

but some day ago api code changed, and I had to change too, and I was thinking was easy adding the the ids:

     def _prepare_full_event(self, distribution, threat_level_id, analysis, info, date=None, published=False, orgc_id=None, org_id=None):
        misp_event = MISPEvent(self.describe_types)
        misp_event.set_all_values(info=info, distribution=distribution, threat_level_id=threat_level_id,
                                  analysis=analysis, date=date, orgc_id=orgc_id, org_id=org_id)

    def new_event(self, distribution=None, threat_level_id=None, analysis=None, info=None, date=None, published=False, orgc_id=None, org_id=None):
        misp_event = self._prepare_full_event(distribution, threat_level_id, analysis, info, date, published, orgc_id=orgc_id, org_id=org_id)
        with open("/tmp/new_event", "w") as f:
            f.write(misp_event)
        return self.add_event(json.dumps(misp_event, cls=EncodeUpdate))

I have no errors but is not working, the only log I can see is in apache and says:
"POST /events/restSearch/download HTTP/1.1" 404 696 "-" "PyMISP 2.4.53"

Do you ahve any idea?

**Comment by Rafiot** [comment]
Your changes are right and that's going to create a valid MISP event.

On the other end, the error you get cannot be related, none of the functions you're using there are calling ` /events/restSearch/download`.

Can you show me the code you're using? 

Also, do not hesitate to make a PR, so we avoid such kind of issues in the future.

**Comment by garanews** [comment]
https://github.com/garanews/PyMISP/commit/edf0cd1d90e89c30a4d3ef756d6bc6501de3885f

**Comment by Rafiot** [comment]
@iglocska not sure what it does on the server side... 

Yeah, we need a way to get the orgs from the server so you can more easily get the proper ID.

**Comment by iglocska** [comment]
Basically: 

orgc_id: the organisation that has created the event
org_id: the local owner of the event

So if for example org A creates an event on misp a and org B that has access to misp a pulls the event to their home instance misp b, the event will become orgc = org A, org = org B

**Comment by Rafiot** [comment]
Fixed: https://github.com/CIRCL/PyMISP/commit/6885779be5424e78976aa40b10aa785df37f0461
