### ISSUE TITLE
No matches witch from_to date function

### ISSUE THREAD

**Issue by s-p01** [CIRCL/PyMISP#7]
Since this morning, I have no result when I try this search : 

```
search = source.search(values=None, not_values=None, type_attribute=None, category=None, org=None, tags=None, not_tags=None, date_from="2014-11-15", date_to="2015-05-15")
```

But with a search by organization attribute for example, it works great.

Any idea ?

**Comment by iglocska** [comment]
Hello s-p01, could you git pull the latest MISP version and try again?

**Comment by s-p01** [comment]
It's ok now, thanks !

**Comment by iglocska** [comment]
My pleasure!

**Comment by Rafiot** [comment]
Fixed \o/
