### ISSUE TITLE
'data' event element not mapped within MISPAttribute

### ISSUE THREAD

**Issue by quoscient** [CIRCL/PyMISP#75]
When parsing 'attributes' out of MISPEvent instances using MISPAttribute, the 'data' element, used to share malware sample is not accessible as object attribute.
As data is base64 encoded, ideally accessing the data attribute would return a decoded byte array.

**Comment by Rafiot** [comment]
here it is: https://github.com/MISP/PyMISP/commit/81faa507f4f03b2ccce132437232fc7216f15122

Can you give a try?

**Comment by quoscient** [comment]
Just reinstalled master and I can't get it, what attribute is it mapped under?

m = pymisp.PyMISP(url, key)
e = pymisp.MISPEvent()
e.load(m.get_event(5445))
a = e.attributes[12]
a.uuid
Out[9]: '58355625-f0d0-4c6e-90b6-5df10a0164ca'
a.type
Out[10]: 'malware-sample'
In [11]: a.data
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-10a7d2617730> in <module>()
----> 1 a.data

AttributeError: 'MISPAttribute' object has no attribute 'data'

**Comment by quoscient** [comment]
Sorry, was wrong repo, got the right branch now and it seems to work.

In [14]: a.data.getbuffer().nbytes
Out[14]: 51273

Thanks!

**Comment by Rafiot** [comment]
Excellent! I'll make a new tag with this update.
