### ISSUE TITLE
misp.search_index returns a different format than misp.search

### ISSUE THREAD

**Issue by cvandeplas** [CIRCL/PyMISP#78]
misp.search() returns an array with objects in the format
`{ 'Event' : {'id': 1, 'info' : "foo" },  ... }`

misp.search_index() returns them without the "Event"  key.

This is confusing when using code, example is both accessing, as using the object later:
With the search():
``` python
result = misp.search(org=org)
for event in result['response']:
    print(event['Event']['id'])
    misp.add_tag(event, tag)
```
And with the search_index:
``` python
result = misp.search_index(org=org)
for event in result['response']:
    print(event['id'])
    misp.add_tag({'Event': event} , tag)
```

**Comment by Rafiot** [comment]
@iglocska can you look at this one? search is the most used function, I think we should normalize on this one.

**Comment by iglocska** [comment]
Yep, that's a nice catch. Will try to get it fixed tonight.

**Comment by Rafiot** [comment]
@iglocska poke? :p

**Comment by PaulSec** [comment]
Wondering @Rafiot how you'd like to normalize? both functions should have the Event key?
