### ISSUE TITLE
allow application of proposal

### ISSUE THREAD

**Issue by cvandeplas** [CIRCL/PyMISP#82]
A nice addition to this marvellous library would be to have an option to the `misp.search()` function to already 'accept' the proposals to attributes.
The order it could be accepted is:  first proposals done by your own organisation, then done by other organisations (if multiple proposals exist)

This is mostly important when doing a `search(controller='attributes')` as when the controller = event you could apply the logic within the python script itself.

**Comment by Rafiot** [comment]
There is now an API to manage proposals.
