### ISSUE TITLE
Warning https

### ISSUE THREAD

**Issue by santi10** [CIRCL/PyMISP#87]
Hi,

I've just received this message:

/usr/local/lib/python2.7/dist-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

My key.api is conifugured so:

`#!/usr/bin/env python
# -*- coding: utf-8 -*-

misp_url = 'https://misp.local/'
misp_key = 'api_key' # The MISP auth key can be found on the MISP web interface under the automation section
misp_verifycert = False`

When I set the script example, I had these message...

Do you known this fix????

Regards

**Comment by Rafiot** [comment]
It is a warning because you don't verify the certificate (`misp_verifycert = False`). It is just a warning and doesn't impact the work of the library. 
You will have an other warning due to the use of Python 2 instead of Python 3.
