### ISSUE TITLE
Add upload file(s) to event

### ISSUE THREAD

**Issue by elhoim** [CIRCL/PyMISP#9]
Add a way to upload a file or multiple files to an existing event, or to a new event created on the fly.

The idea is to be able to do something like ./script.py --upload-files ./samples/ --event 761

All the better if this functionality allows to select the category, the distribution level of the files and "malware" zipping.

**Comment by elhoim** [comment]
Related to https://github.com/MISP/MISP/issues/244.

**Comment by Rafiot** [comment]
Nice, I will work on it ASAP

**Comment by Rafiot** [comment]
WIP: bef354ac4431bbb50546c2bb9b6a68a38bd04a82
https://github.com/CIRCL/PyMISP/blob/master/examples/upload.py

**Comment by Rafiot** [comment]
Fixed. Also possible to do it via Viper.
