### ISSUE TITLE
Issues with adding new attributes to update_event method

### ISSUE THREAD

**Issue by cyber-guy** [CIRCL/PyMISP#90]
I am attempting to utilize the update_event(event_id, event) method to add a list of new attributes to an existing event. I pass the event ID and a JSON string formatted as similar to the below example:

{ "Attribute :  [ {  "<key>" : "<value>", "<key>" : "<value>" }, {  "<key>" : "<value>", "<key>" : "<value>" } ] }

I don't receive any errors but the attributes do not get added to the event. I don't have any issues updating the high level components of the event, like "distribution", with this method, but just cannot get it to save attributes. Does update_event expect more JSON components then I am passing or is it not meant to update the event at this kind of a level?

**Comment by Rafiot** [comment]
You should use `add_named_attribute` (https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L415) or pass a MISPEvent to `update` https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L338

**Comment by cyber-guy** [comment]
Thank you for the suggestion. I guess I just wasn't understanding the documentation surrounding what update_event was expecting because i was able to pass it partial JSON in the event field (example: { { "Event" : { "distribution" : "1", "published" : True } and that would work, but it wasn't liking when i tried to add the Attribute details.

Either way, the suggestions you gave work and I appreciate the help. Thanks again.
