### ISSUE TITLE
Sample file altered when using upload_sample

### ISSUE THREAD

**Issue by jymcheong** [CIRCL/PyMISP#91]
<img width="1090" alt="screenshot 2017-03-20 13 08 38" src="https://cloud.githubusercontent.com/assets/11232021/24089163/681485e4-0d6e-11e7-8175-6de9dc463461.png">

The sample with correct hash '5dbf819539ae860f0d52797ebf0a3a5f' is uploaded via 'Add Attachment' whereas the other one is via PyMISP upload_sample. 

Code used:
`r = m.upload_sample(sample_fname, '/some/path/' + sample_fname, None, None, True, None, None, row[1], None, severity)`

Code works since a new event is created with attributes related to the uploaded file.

MISP 2.4.67
pymisp-2.4.67-py3.4

**Comment by Rafiot** [comment]
A sample is automatically compressed and encrypted with a password ("infected").

But I don't understand why the type is "malware-sample" if you used add_attachment method.

**Comment by jymcheong** [comment]
When I upload via web interface, it has always been Payload Delivery : malware-sample. I check IDS checkbox. When I don't check IDS checkbox, the attachment is as it is without zipping + password.

Anyway, I tested my python script in another VM (same script + same payload since they are automatically sync), the upload_sample works fine. So I suspect something is wrong with my laptop VM. 

The differences are:
MISP 2.4.69
pymisp-2.4.68

**Comment by iglocska** [comment]
Add attachment allows you to select attachments / malware-samples that far it's correct. Weird why it would end up being something different. I wonder if there isn't something I forgot to implement on MISP's side to handle the malware-sample's coming from pyMISP.

**Comment by jymcheong** [comment]
I narrowed down to:

`    def _encode_file_to_upload(self, path):
        with open(path, 'rb') as f:
            return str(base64.b64encode(f.read()))` 

Which is fine & should not be an issue. After testing the batch upload with another VM in another environment. The checksums are all correct. Which leads me to think it is my first VM's environment issue.

**Comment by jymcheong** [comment]
Upgraded my laptop VM to  MISP 2.4.69 & pymisp-2.4.68, the checksums are correct after PyMISP upload_sample().
