### ISSUE TITLE
"up.py" bad description // Importance LOW

### ISSUE THREAD

**Issue by Tux-Panik** [CIRCL/PyMISP#92]
Hello,

I think we have a mistake in "up.py" script: [https://github.com/CIRCL/PyMISP/blob/master/examples/up.py](https://github.com/CIRCL/PyMISP/blob/master/examples/up.py).

> Usage for pipe masters: ./**last.py** -l 5h | jq .
[...]
>  parser = argparse.ArgumentParser(description='**Get an event from a MISP instance**.')
>  parser.add_argument("-e", "--event", required=True, help="**Event ID to get.**")
>  parser.add_argument("-i", "--input", required=True, help="Input file")

Regards,

**Comment by FloatingGhost** [comment]
You're quite right - this script *updates* an event :D 

I'll go fix that

**Comment by FloatingGhost** [comment]
Fixed in CIRCL/3da2a54

**Comment by Rafiot** [comment]
Thanks! :)
