### ISSUE TITLE
Decprecated functions break PyMISP

### ISSUE THREAD

**Issue by RichieB2B** [CIRCL/PyMISP#94]
Trying to use the add_tag function with PyMISP 2.4.68 fails with:
```
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pymisp/api.py", line 55, in new_func
    filename=func.func_code.co_filename,
AttributeError: 'function' object has no attribute 'func_code'
```

**Comment by Rafiot** [comment]
Woops, sorry for that.

I just pushed a fix (not tested). Can you confirm it's fine?

**Comment by RichieB2B** [comment]
Thanks. The error is gone, add_tag() still works as expected, but no warning is shown either.

**Comment by Rafiot** [comment]
.... okay, I'll spend some more time on it then..
