### ISSUE TITLE
MISP remove_tag broken

### ISSUE THREAD

**Issue by mohl1** [CIRCL/PyMISP#96]
Hi All, 
tried to add and remove tags on a MISP event with v2.4.68. The misp.add_tag seems to be working fine. However to remove a tag with misp.remove_tag doesn't work. Made the same experience with IntelMQ and the PyMISP v2.4.68.zip.

really simple test with:

```
def init(url, key):
      return PyMISP(url, key, False, 'json', debug=False)

misp = init(misp_url, misp_key)
event = misp.get_event("622")
misp.remove_tag(event, str("ATD:Report"))
```

Did someone experience the same?
All the best,

**Comment by Rafiot** [comment]
Sorry for that, it is now patched: https://github.com/CIRCL/PyMISP/commit/f6dc99175181888bcda3f427fea7e3a88d429f74

To use it, you will need to install from repository:

```
pip install git+https://github.com/CIRCL/PyMISP.git
```
