### ISSUE TITLE
UnboundLocalError when empty attribute is added

### ISSUE THREAD

**Issue by RichieB2B** [CIRCL/PyMISP#97]
In [_send_attributes()](https://github.com/CIRCL/PyMISP/blob/master/pymisp/api.py#L414) when attributes is an empty list, response is not set. This results is:
```
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pymisp/api.py", line 446, in add_hashes
    return self._send_attributes(event, attributes, proposal)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/pymisp/api.py", line 421, in _send_attributes
    return response
UnboundLocalError: local variable 'response' referenced before assignment
```
Instead a friendly error should be returned.

**Comment by Rafiot** [comment]
Okay, this will be slightly more broken than I was expecting: 
* it only returns the response of the last attribute added
* it does N posts (with N == len(attributes)) instead of posting all the attributes at once

**Comment by RichieB2B** [comment]
That sounds bad, performance wise. Can't you just fix it for N==0 to avoid the UnboundLocalError?

**Comment by Rafiot** [comment]
Done.

It's not clean and I need to improve that function.

**Comment by Rafiot** [comment]
Moved over there: https://github.com/MISP/PyMISP/issues/137
