### ISSUE TITLE
delete single attribute from all events

### ISSUE THREAD

**Issue by garanews** [CIRCL/PyMISP#98]
How can I delete an attribute wrongly inserted in many events?

**Comment by garanews** [comment]
I created the delete script but I need to increase the timeout of the search:

  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Connection Timed Out

Do you know how?

**Comment by Rafiot** [comment]
I'm not sure what you mean. `Connection Timed Out` sounds like you have issues to reach the server.

If you just want to be nicer to the server and not do too many queries/sec, you can add a sleep.
